/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PaysafeApi);
  }
}(this, function(expect, PaysafeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PaysafeApi.Deposits();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Deposits', function() {
    it('should create an instance of Deposits', function() {
      // uncomment below and update the code to test Deposits
      //var instance = new PaysafeApi.Deposits();
      //expect(instance).to.be.a(PaysafeApi.Deposits);
    });

    it('should have the property despositType (base name: "desposit_type")', function() {
      // uncomment below and update the code to test the property despositType
      //var instance = new PaysafeApi.Deposits();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new PaysafeApi.Deposits();
      //expect(instance).to.be();
    });

    it('should have the property accountName (base name: "account_name")', function() {
      // uncomment below and update the code to test the property accountName
      //var instance = new PaysafeApi.Deposits();
      //expect(instance).to.be();
    });

    it('should have the property accountNumber (base name: "account_number")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instance = new PaysafeApi.Deposits();
      //expect(instance).to.be();
    });

    it('should have the property routingNumber (base name: "routing_number")', function() {
      // uncomment below and update the code to test the property routingNumber
      //var instance = new PaysafeApi.Deposits();
      //expect(instance).to.be();
    });

    it('should have the property instutionId (base name: "instution_id")', function() {
      // uncomment below and update the code to test the property instutionId
      //var instance = new PaysafeApi.Deposits();
      //expect(instance).to.be();
    });

  });

}));
