/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PaysafeApi);
  }
}(this, function(expect, PaysafeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PaysafeApi.Documents();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Documents', function() {
    it('should create an instance of Documents', function() {
      // uncomment below and update the code to test Documents
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be.a(PaysafeApi.Documents);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "number")', function() {
      // uncomment below and update the code to test the property _number
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property issuedby (base name: "issuedby")', function() {
      // uncomment below and update the code to test the property issuedby
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property issuedDay (base name: "issued_day")', function() {
      // uncomment below and update the code to test the property issuedDay
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property issuedMonth (base name: "issued_month")', function() {
      // uncomment below and update the code to test the property issuedMonth
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property issuedYear (base name: "issued_year")', function() {
      // uncomment below and update the code to test the property issuedYear
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property expiresDay (base name: "expires_day")', function() {
      // uncomment below and update the code to test the property expiresDay
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property expiresMonth (base name: "expires_month")', function() {
      // uncomment below and update the code to test the property expiresMonth
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

    it('should have the property expiresYear (base name: "expires_year")', function() {
      // uncomment below and update the code to test the property expiresYear
      //var instance = new PaysafeApi.Documents();
      //expect(instance).to.be();
    });

  });

}));
