/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PaysafeApi);
  }
}(this, function(expect, PaysafeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PaysafeApi.Owner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Owner', function() {
    it('should create an instance of Owner', function() {
      // uncomment below and update the code to test Owner
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be.a(PaysafeApi.Owner);
    });

    it('should have the property ownerCtime (base name: "owner_ctime")', function() {
      // uncomment below and update the code to test the property ownerCtime
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerAddress (base name: "owner_address")', function() {
      // uncomment below and update the code to test the property ownerAddress
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerAddress2 (base name: "owner_address2")', function() {
      // uncomment below and update the code to test the property ownerAddress2
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerCity (base name: "owner_city")', function() {
      // uncomment below and update the code to test the property ownerCity
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerState (base name: "owner_state")', function() {
      // uncomment below and update the code to test the property ownerState
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerZip (base name: "owner_zip")', function() {
      // uncomment below and update the code to test the property ownerZip
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerZip4 (base name: "owner_zip4")', function() {
      // uncomment below and update the code to test the property ownerZip4
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerPtime (base name: "owner_ptime")', function() {
      // uncomment below and update the code to test the property ownerPtime
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerPaddress (base name: "owner_paddress")', function() {
      // uncomment below and update the code to test the property ownerPaddress
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerPaddress2 (base name: "owner_paddress2")', function() {
      // uncomment below and update the code to test the property ownerPaddress2
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerPcity (base name: "owner_pcity")', function() {
      // uncomment below and update the code to test the property ownerPcity
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerPstate (base name: "owner_pstate")', function() {
      // uncomment below and update the code to test the property ownerPstate
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerPzip (base name: "owner_pzip")', function() {
      // uncomment below and update the code to test the property ownerPzip
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

    it('should have the property ownerPzip4 (base name: "owner_pzip4")', function() {
      // uncomment below and update the code to test the property ownerPzip4
      //var instance = new PaysafeApi.Owner();
      //expect(instance).to.be();
    });

  });

}));
