/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PaysafeApi);
  }
}(this, function(expect, PaysafeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PaysafeApi.Ownerr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Ownerr', function() {
    it('should create an instance of Ownerr', function() {
      // uncomment below and update the code to test Ownerr
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be.a(PaysafeApi.Ownerr);
    });

    it('should have the property nameFirst (base name: "name_first")', function() {
      // uncomment below and update the code to test the property nameFirst
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property nameLast (base name: "name_last")', function() {
      // uncomment below and update the code to test the property nameLast
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property jobTitle (base name: "job_title")', function() {
      // uncomment below and update the code to test the property jobTitle
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property day (base name: "day")', function() {
      // uncomment below and update the code to test the property day
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property month (base name: "month")', function() {
      // uncomment below and update the code to test the property month
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property nationality (base name: "nationality")', function() {
      // uncomment below and update the code to test the property nationality
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property taxid (base name: "taxid")', function() {
      // uncomment below and update the code to test the property taxid
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

    it('should have the property percentage (base name: "percentage")', function() {
      // uncomment below and update the code to test the property percentage
      //var instance = new PaysafeApi.Ownerr();
      //expect(instance).to.be();
    });

  });

}));
