/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PaysafeApi);
  }
}(this, function(expect, PaysafeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PaysafeApi.Transaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Transaction', function() {
    it('should create an instance of Transaction', function() {
      // uncomment below and update the code to test Transaction
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be.a(PaysafeApi.Transaction);
    });

    it('should have the property trxVolume (base name: "trx_volume")', function() {
      // uncomment below and update the code to test the property trxVolume
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property trxAverage (base name: "trx_average")', function() {
      // uncomment below and update the code to test the property trxAverage
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property trxHigh (base name: "trx_high")', function() {
      // uncomment below and update the code to test the property trxHigh
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property previouslyAccepted (base name: "previously_accepted")', function() {
      // uncomment below and update the code to test the property previouslyAccepted
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property acceptance (base name: "acceptance")', function() {
      // uncomment below and update the code to test the property acceptance
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property cardPresent (base name: "card_present")', function() {
      // uncomment below and update the code to test the property cardPresent
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property shipGoods (base name: "ship_goods")', function() {
      // uncomment below and update the code to test the property shipGoods
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property deliveryTime (base name: "delivery_time")', function() {
      // uncomment below and update the code to test the property deliveryTime
      //var instance = new PaysafeApi.Transaction();
      //expect(instance).to.be();
    });

  });

}));
