/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PaysafeApi);
  }
}(this, function(expect, PaysafeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PaysafeApi.Updatecontact();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Updatecontact', function() {
    it('should create an instance of Updatecontact', function() {
      // uncomment below and update the code to test Updatecontact
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be.a(PaysafeApi.Updatecontact);
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property companyLegal (base name: "company_legal")', function() {
      // uncomment below and update the code to test the property companyLegal
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property address2 (base name: "address2")', function() {
      // uncomment below and update the code to test the property address2
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property zip4 (base name: "zip4")', function() {
      // uncomment below and update the code to test the property zip4
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phone_number")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property pAddress (base name: "p_address")', function() {
      // uncomment below and update the code to test the property pAddress
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property pAddress2 (base name: "p_address2")', function() {
      // uncomment below and update the code to test the property pAddress2
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property pCity (base name: "p_city")', function() {
      // uncomment below and update the code to test the property pCity
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property pState (base name: "p_state")', function() {
      // uncomment below and update the code to test the property pState
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property pPostalCode (base name: "p_postal_code")', function() {
      // uncomment below and update the code to test the property pPostalCode
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

    it('should have the property pZip4 (base name: "p_zip4")', function() {
      // uncomment below and update the code to test the property pZip4
      //var instance = new PaysafeApi.Updatecontact();
      //expect(instance).to.be();
    });

  });

}));
