# coding: utf-8

"""
    Paysafe Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Setting(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'str',
        'amex_id': 'str',
        'descriptor': 'str',
        'locale': 'str',
        'lang': 'str',
        'descriptor_phone': 'str'
    }

    attribute_map = {
        'currency': 'currency',
        'amex_id': 'amex_id',
        'descriptor': 'descriptor',
        'locale': 'locale',
        'lang': 'lang',
        'descriptor_phone': 'descriptor_phone'
    }

    def __init__(self, currency=None, amex_id=None, descriptor=None, locale=None, lang=None, descriptor_phone=None):  # noqa: E501
        """Setting - a model defined in Swagger"""  # noqa: E501

        self._currency = None
        self._amex_id = None
        self._descriptor = None
        self._locale = None
        self._lang = None
        self._descriptor_phone = None
        self.discriminator = None

        self.currency = currency
        self.amex_id = amex_id
        self.descriptor = descriptor
        self.locale = locale
        self.lang = lang
        self.descriptor_phone = descriptor_phone

    @property
    def currency(self):
        """Gets the currency of this Setting.  # noqa: E501


        :return: The currency of this Setting.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this Setting.


        :param currency: The currency of this Setting.  # noqa: E501
        :type: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501

        self._currency = currency

    @property
    def amex_id(self):
        """Gets the amex_id of this Setting.  # noqa: E501


        :return: The amex_id of this Setting.  # noqa: E501
        :rtype: str
        """
        return self._amex_id

    @amex_id.setter
    def amex_id(self, amex_id):
        """Sets the amex_id of this Setting.


        :param amex_id: The amex_id of this Setting.  # noqa: E501
        :type: str
        """
        if amex_id is None:
            raise ValueError("Invalid value for `amex_id`, must not be `None`")  # noqa: E501

        self._amex_id = amex_id

    @property
    def descriptor(self):
        """Gets the descriptor of this Setting.  # noqa: E501


        :return: The descriptor of this Setting.  # noqa: E501
        :rtype: str
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor):
        """Sets the descriptor of this Setting.


        :param descriptor: The descriptor of this Setting.  # noqa: E501
        :type: str
        """
        if descriptor is None:
            raise ValueError("Invalid value for `descriptor`, must not be `None`")  # noqa: E501

        self._descriptor = descriptor

    @property
    def locale(self):
        """Gets the locale of this Setting.  # noqa: E501


        :return: The locale of this Setting.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Setting.


        :param locale: The locale of this Setting.  # noqa: E501
        :type: str
        """
        if locale is None:
            raise ValueError("Invalid value for `locale`, must not be `None`")  # noqa: E501

        self._locale = locale

    @property
    def lang(self):
        """Gets the lang of this Setting.  # noqa: E501


        :return: The lang of this Setting.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this Setting.


        :param lang: The lang of this Setting.  # noqa: E501
        :type: str
        """
        if lang is None:
            raise ValueError("Invalid value for `lang`, must not be `None`")  # noqa: E501

        self._lang = lang

    @property
    def descriptor_phone(self):
        """Gets the descriptor_phone of this Setting.  # noqa: E501


        :return: The descriptor_phone of this Setting.  # noqa: E501
        :rtype: str
        """
        return self._descriptor_phone

    @descriptor_phone.setter
    def descriptor_phone(self, descriptor_phone):
        """Sets the descriptor_phone of this Setting.


        :param descriptor_phone: The descriptor_phone of this Setting.  # noqa: E501
        :type: str
        """
        if descriptor_phone is None:
            raise ValueError("Invalid value for `descriptor_phone`, must not be `None`")  # noqa: E501

        self._descriptor_phone = descriptor_phone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Setting):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
