# coding: utf-8

"""
    Paysafe Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Updatecompany(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lang': 'str',
        'name': 'str',
        'tz': 'str'
    }

    attribute_map = {
        'lang': 'lang',
        'name': 'name',
        'tz': 'tz'
    }

    def __init__(self, lang=None, name=None, tz=None):  # noqa: E501
        """Updatecompany - a model defined in Swagger"""  # noqa: E501

        self._lang = None
        self._name = None
        self._tz = None
        self.discriminator = None

        self.lang = lang
        self.name = name
        self.tz = tz

    @property
    def lang(self):
        """Gets the lang of this Updatecompany.  # noqa: E501


        :return: The lang of this Updatecompany.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this Updatecompany.


        :param lang: The lang of this Updatecompany.  # noqa: E501
        :type: str
        """
        if lang is None:
            raise ValueError("Invalid value for `lang`, must not be `None`")  # noqa: E501

        self._lang = lang

    @property
    def name(self):
        """Gets the name of this Updatecompany.  # noqa: E501


        :return: The name of this Updatecompany.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Updatecompany.


        :param name: The name of this Updatecompany.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def tz(self):
        """Gets the tz of this Updatecompany.  # noqa: E501


        :return: The tz of this Updatecompany.  # noqa: E501
        :rtype: str
        """
        return self._tz

    @tz.setter
    def tz(self, tz):
        """Sets the tz of this Updatecompany.


        :param tz: The tz of this Updatecompany.  # noqa: E501
        :type: str
        """
        if tz is None:
            raise ValueError("Invalid value for `tz`, must not be `None`")  # noqa: E501

        self._tz = tz

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Updatecompany):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
