/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaysafeApi) {
      root.PaysafeApi = {};
    }
    root.PaysafeApi.Deposits = factory(root.PaysafeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Deposits model module.
   * @module model/Deposits
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Deposits</code>.
   * @alias module:model/Deposits
   * @class
   * @param despositType {String} 
   * @param country {String} 
   * @param accountName {String} 
   * @param accountNumber {String} 
   * @param routingNumber {String} 
   * @param instutionId {String} 
   */
  var exports = function(despositType, country, accountName, accountNumber, routingNumber, instutionId) {
    var _this = this;

    _this['desposit_type'] = despositType;
    _this['country'] = country;
    _this['account_name'] = accountName;
    _this['account_number'] = accountNumber;
    _this['routing_number'] = routingNumber;
    _this['instution_id'] = instutionId;
  };

  /**
   * Constructs a <code>Deposits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Deposits} obj Optional instance to populate.
   * @return {module:model/Deposits} The populated <code>Deposits</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('desposit_type')) {
        obj['desposit_type'] = ApiClient.convertToType(data['desposit_type'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('account_name')) {
        obj['account_name'] = ApiClient.convertToType(data['account_name'], 'String');
      }
      if (data.hasOwnProperty('account_number')) {
        obj['account_number'] = ApiClient.convertToType(data['account_number'], 'String');
      }
      if (data.hasOwnProperty('routing_number')) {
        obj['routing_number'] = ApiClient.convertToType(data['routing_number'], 'String');
      }
      if (data.hasOwnProperty('instution_id')) {
        obj['instution_id'] = ApiClient.convertToType(data['instution_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} desposit_type
   */
  exports.prototype['desposit_type'] = undefined;
  /**
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * @member {String} account_name
   */
  exports.prototype['account_name'] = undefined;
  /**
   * @member {String} account_number
   */
  exports.prototype['account_number'] = undefined;
  /**
   * @member {String} routing_number
   */
  exports.prototype['routing_number'] = undefined;
  /**
   * @member {String} instution_id
   */
  exports.prototype['instution_id'] = undefined;



  return exports;
}));


