/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaysafeApi) {
      root.PaysafeApi = {};
    }
    root.PaysafeApi.Documents = factory(root.PaysafeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Documents model module.
   * @module model/Documents
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Documents</code>.
   * @alias module:model/Documents
   * @class
   * @param type {String} 
   * @param _number {String} 
   * @param issuedby {String} 
   * @param issuedDay {String} 
   * @param issuedMonth {String} 
   * @param issuedYear {String} 
   * @param expiresDay {String} 
   * @param expiresMonth {String} 
   * @param expiresYear {String} 
   */
  var exports = function(type, _number, issuedby, issuedDay, issuedMonth, issuedYear, expiresDay, expiresMonth, expiresYear) {
    var _this = this;

    _this['type'] = type;
    _this['number'] = _number;
    _this['issuedby'] = issuedby;
    _this['issued_day'] = issuedDay;
    _this['issued_month'] = issuedMonth;
    _this['issued_year'] = issuedYear;
    _this['expires_day'] = expiresDay;
    _this['expires_month'] = expiresMonth;
    _this['expires_year'] = expiresYear;
  };

  /**
   * Constructs a <code>Documents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Documents} obj Optional instance to populate.
   * @return {module:model/Documents} The populated <code>Documents</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('number')) {
        obj['number'] = ApiClient.convertToType(data['number'], 'String');
      }
      if (data.hasOwnProperty('issuedby')) {
        obj['issuedby'] = ApiClient.convertToType(data['issuedby'], 'String');
      }
      if (data.hasOwnProperty('issued_day')) {
        obj['issued_day'] = ApiClient.convertToType(data['issued_day'], 'String');
      }
      if (data.hasOwnProperty('issued_month')) {
        obj['issued_month'] = ApiClient.convertToType(data['issued_month'], 'String');
      }
      if (data.hasOwnProperty('issued_year')) {
        obj['issued_year'] = ApiClient.convertToType(data['issued_year'], 'String');
      }
      if (data.hasOwnProperty('expires_day')) {
        obj['expires_day'] = ApiClient.convertToType(data['expires_day'], 'String');
      }
      if (data.hasOwnProperty('expires_month')) {
        obj['expires_month'] = ApiClient.convertToType(data['expires_month'], 'String');
      }
      if (data.hasOwnProperty('expires_year')) {
        obj['expires_year'] = ApiClient.convertToType(data['expires_year'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} number
   */
  exports.prototype['number'] = undefined;
  /**
   * @member {String} issuedby
   */
  exports.prototype['issuedby'] = undefined;
  /**
   * @member {String} issued_day
   */
  exports.prototype['issued_day'] = undefined;
  /**
   * @member {String} issued_month
   */
  exports.prototype['issued_month'] = undefined;
  /**
   * @member {String} issued_year
   */
  exports.prototype['issued_year'] = undefined;
  /**
   * @member {String} expires_day
   */
  exports.prototype['expires_day'] = undefined;
  /**
   * @member {String} expires_month
   */
  exports.prototype['expires_month'] = undefined;
  /**
   * @member {String} expires_year
   */
  exports.prototype['expires_year'] = undefined;



  return exports;
}));


