/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaysafeApi) {
      root.PaysafeApi = {};
    }
    root.PaysafeApi.Owner = factory(root.PaysafeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Owner model module.
   * @module model/Owner
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Owner</code>.
   * @alias module:model/Owner
   * @class
   * @param ownerCtime {String} 
   * @param ownerAddress {String} 
   * @param ownerAddress2 {String} 
   * @param ownerCity {String} 
   * @param ownerState {String} 
   * @param ownerZip {String} 
   * @param ownerZip4 {String} 
   * @param ownerPtime {String} 
   * @param ownerPaddress {String} 
   * @param ownerPaddress2 {String} 
   * @param ownerPcity {String} 
   * @param ownerPstate {String} 
   * @param ownerPzip {String} 
   * @param ownerPzip4 {String} 
   */
  var exports = function(ownerCtime, ownerAddress, ownerAddress2, ownerCity, ownerState, ownerZip, ownerZip4, ownerPtime, ownerPaddress, ownerPaddress2, ownerPcity, ownerPstate, ownerPzip, ownerPzip4) {
    var _this = this;

    _this['owner_ctime'] = ownerCtime;
    _this['owner_address'] = ownerAddress;
    _this['owner_address2'] = ownerAddress2;
    _this['owner_city'] = ownerCity;
    _this['owner_state'] = ownerState;
    _this['owner_zip'] = ownerZip;
    _this['owner_zip4'] = ownerZip4;
    _this['owner_ptime'] = ownerPtime;
    _this['owner_paddress'] = ownerPaddress;
    _this['owner_paddress2'] = ownerPaddress2;
    _this['owner_pcity'] = ownerPcity;
    _this['owner_pstate'] = ownerPstate;
    _this['owner_pzip'] = ownerPzip;
    _this['owner_pzip4'] = ownerPzip4;
  };

  /**
   * Constructs a <code>Owner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Owner} obj Optional instance to populate.
   * @return {module:model/Owner} The populated <code>Owner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('owner_ctime')) {
        obj['owner_ctime'] = ApiClient.convertToType(data['owner_ctime'], 'String');
      }
      if (data.hasOwnProperty('owner_address')) {
        obj['owner_address'] = ApiClient.convertToType(data['owner_address'], 'String');
      }
      if (data.hasOwnProperty('owner_address2')) {
        obj['owner_address2'] = ApiClient.convertToType(data['owner_address2'], 'String');
      }
      if (data.hasOwnProperty('owner_city')) {
        obj['owner_city'] = ApiClient.convertToType(data['owner_city'], 'String');
      }
      if (data.hasOwnProperty('owner_state')) {
        obj['owner_state'] = ApiClient.convertToType(data['owner_state'], 'String');
      }
      if (data.hasOwnProperty('owner_zip')) {
        obj['owner_zip'] = ApiClient.convertToType(data['owner_zip'], 'String');
      }
      if (data.hasOwnProperty('owner_zip4')) {
        obj['owner_zip4'] = ApiClient.convertToType(data['owner_zip4'], 'String');
      }
      if (data.hasOwnProperty('owner_ptime')) {
        obj['owner_ptime'] = ApiClient.convertToType(data['owner_ptime'], 'String');
      }
      if (data.hasOwnProperty('owner_paddress')) {
        obj['owner_paddress'] = ApiClient.convertToType(data['owner_paddress'], 'String');
      }
      if (data.hasOwnProperty('owner_paddress2')) {
        obj['owner_paddress2'] = ApiClient.convertToType(data['owner_paddress2'], 'String');
      }
      if (data.hasOwnProperty('owner_pcity')) {
        obj['owner_pcity'] = ApiClient.convertToType(data['owner_pcity'], 'String');
      }
      if (data.hasOwnProperty('owner_pstate')) {
        obj['owner_pstate'] = ApiClient.convertToType(data['owner_pstate'], 'String');
      }
      if (data.hasOwnProperty('owner_pzip')) {
        obj['owner_pzip'] = ApiClient.convertToType(data['owner_pzip'], 'String');
      }
      if (data.hasOwnProperty('owner_pzip4')) {
        obj['owner_pzip4'] = ApiClient.convertToType(data['owner_pzip4'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} owner_ctime
   */
  exports.prototype['owner_ctime'] = undefined;
  /**
   * @member {String} owner_address
   */
  exports.prototype['owner_address'] = undefined;
  /**
   * @member {String} owner_address2
   */
  exports.prototype['owner_address2'] = undefined;
  /**
   * @member {String} owner_city
   */
  exports.prototype['owner_city'] = undefined;
  /**
   * @member {String} owner_state
   */
  exports.prototype['owner_state'] = undefined;
  /**
   * @member {String} owner_zip
   */
  exports.prototype['owner_zip'] = undefined;
  /**
   * @member {String} owner_zip4
   */
  exports.prototype['owner_zip4'] = undefined;
  /**
   * @member {String} owner_ptime
   */
  exports.prototype['owner_ptime'] = undefined;
  /**
   * @member {String} owner_paddress
   */
  exports.prototype['owner_paddress'] = undefined;
  /**
   * @member {String} owner_paddress2
   */
  exports.prototype['owner_paddress2'] = undefined;
  /**
   * @member {String} owner_pcity
   */
  exports.prototype['owner_pcity'] = undefined;
  /**
   * @member {String} owner_pstate
   */
  exports.prototype['owner_pstate'] = undefined;
  /**
   * @member {String} owner_pzip
   */
  exports.prototype['owner_pzip'] = undefined;
  /**
   * @member {String} owner_pzip4
   */
  exports.prototype['owner_pzip4'] = undefined;



  return exports;
}));


