/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaysafeApi) {
      root.PaysafeApi = {};
    }
    root.PaysafeApi.Setting = factory(root.PaysafeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Setting model module.
   * @module model/Setting
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Setting</code>.
   * @alias module:model/Setting
   * @class
   * @param currency {String} 
   * @param amexId {String} 
   * @param descriptor {String} 
   * @param locale {String} 
   * @param lang {String} 
   * @param descriptorPhone {String} 
   */
  var exports = function(currency, amexId, descriptor, locale, lang, descriptorPhone) {
    var _this = this;

    _this['currency'] = currency;
    _this['amex_id'] = amexId;
    _this['descriptor'] = descriptor;
    _this['locale'] = locale;
    _this['lang'] = lang;
    _this['descriptor_phone'] = descriptorPhone;
  };

  /**
   * Constructs a <code>Setting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Setting} obj Optional instance to populate.
   * @return {module:model/Setting} The populated <code>Setting</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('amex_id')) {
        obj['amex_id'] = ApiClient.convertToType(data['amex_id'], 'String');
      }
      if (data.hasOwnProperty('descriptor')) {
        obj['descriptor'] = ApiClient.convertToType(data['descriptor'], 'String');
      }
      if (data.hasOwnProperty('locale')) {
        obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
      }
      if (data.hasOwnProperty('lang')) {
        obj['lang'] = ApiClient.convertToType(data['lang'], 'String');
      }
      if (data.hasOwnProperty('descriptor_phone')) {
        obj['descriptor_phone'] = ApiClient.convertToType(data['descriptor_phone'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {String} amex_id
   */
  exports.prototype['amex_id'] = undefined;
  /**
   * @member {String} descriptor
   */
  exports.prototype['descriptor'] = undefined;
  /**
   * @member {String} locale
   */
  exports.prototype['locale'] = undefined;
  /**
   * @member {String} lang
   */
  exports.prototype['lang'] = undefined;
  /**
   * @member {String} descriptor_phone
   */
  exports.prototype['descriptor_phone'] = undefined;



  return exports;
}));


