/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaysafeApi) {
      root.PaysafeApi = {};
    }
    root.PaysafeApi.Transaction = factory(root.PaysafeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Transaction model module.
   * @module model/Transaction
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Transaction</code>.
   * @alias module:model/Transaction
   * @class
   * @param trxVolume {String} 
   * @param trxAverage {String} 
   * @param trxHigh {String} 
   * @param previouslyAccepted {String} 
   * @param acceptance {String} 
   * @param cardPresent {String} 
   * @param shipGoods {String} 
   * @param deliveryTime {String} 
   */
  var exports = function(trxVolume, trxAverage, trxHigh, previouslyAccepted, acceptance, cardPresent, shipGoods, deliveryTime) {
    var _this = this;

    _this['trx_volume'] = trxVolume;
    _this['trx_average'] = trxAverage;
    _this['trx_high'] = trxHigh;
    _this['previously_accepted'] = previouslyAccepted;
    _this['acceptance'] = acceptance;
    _this['card_present'] = cardPresent;
    _this['ship_goods'] = shipGoods;
    _this['delivery_time'] = deliveryTime;
  };

  /**
   * Constructs a <code>Transaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transaction} obj Optional instance to populate.
   * @return {module:model/Transaction} The populated <code>Transaction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('trx_volume')) {
        obj['trx_volume'] = ApiClient.convertToType(data['trx_volume'], 'String');
      }
      if (data.hasOwnProperty('trx_average')) {
        obj['trx_average'] = ApiClient.convertToType(data['trx_average'], 'String');
      }
      if (data.hasOwnProperty('trx_high')) {
        obj['trx_high'] = ApiClient.convertToType(data['trx_high'], 'String');
      }
      if (data.hasOwnProperty('previously_accepted')) {
        obj['previously_accepted'] = ApiClient.convertToType(data['previously_accepted'], 'String');
      }
      if (data.hasOwnProperty('acceptance')) {
        obj['acceptance'] = ApiClient.convertToType(data['acceptance'], 'String');
      }
      if (data.hasOwnProperty('card_present')) {
        obj['card_present'] = ApiClient.convertToType(data['card_present'], 'String');
      }
      if (data.hasOwnProperty('ship_goods')) {
        obj['ship_goods'] = ApiClient.convertToType(data['ship_goods'], 'String');
      }
      if (data.hasOwnProperty('delivery_time')) {
        obj['delivery_time'] = ApiClient.convertToType(data['delivery_time'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} trx_volume
   */
  exports.prototype['trx_volume'] = undefined;
  /**
   * @member {String} trx_average
   */
  exports.prototype['trx_average'] = undefined;
  /**
   * @member {String} trx_high
   */
  exports.prototype['trx_high'] = undefined;
  /**
   * @member {String} previously_accepted
   */
  exports.prototype['previously_accepted'] = undefined;
  /**
   * @member {String} acceptance
   */
  exports.prototype['acceptance'] = undefined;
  /**
   * @member {String} card_present
   */
  exports.prototype['card_present'] = undefined;
  /**
   * @member {String} ship_goods
   */
  exports.prototype['ship_goods'] = undefined;
  /**
   * @member {String} delivery_time
   */
  exports.prototype['delivery_time'] = undefined;



  return exports;
}));


