/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaysafeApi) {
      root.PaysafeApi = {};
    }
    root.PaysafeApi.Updateuser = factory(root.PaysafeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Updateuser model module.
   * @module model/Updateuser
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Updateuser</code>.
   * @alias module:model/Updateuser
   * @class
   * @param nameFirst {String} 
   * @param nameLast {String} 
   * @param email {String} 
   * @param login {String} 
   */
  var exports = function(nameFirst, nameLast, email, login) {
    var _this = this;

    _this['name_first'] = nameFirst;
    _this['name_last'] = nameLast;
    _this['email'] = email;
    _this['login'] = login;
  };

  /**
   * Constructs a <code>Updateuser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Updateuser} obj Optional instance to populate.
   * @return {module:model/Updateuser} The populated <code>Updateuser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name_first')) {
        obj['name_first'] = ApiClient.convertToType(data['name_first'], 'String');
      }
      if (data.hasOwnProperty('name_last')) {
        obj['name_last'] = ApiClient.convertToType(data['name_last'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('login')) {
        obj['login'] = ApiClient.convertToType(data['login'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name_first
   */
  exports.prototype['name_first'] = undefined;
  /**
   * @member {String} name_last
   */
  exports.prototype['name_last'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} login
   */
  exports.prototype['login'] = undefined;



  return exports;
}));


