/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaysafeApi) {
      root.PaysafeApi = {};
    }
    root.PaysafeApi.Updatecontact = factory(root.PaysafeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Updatecontact model module.
   * @module model/Updatecontact
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Updatecontact</code>.
   * @alias module:model/Updatecontact
   * @class
   * @param companyName {String} 
   * @param companyLegal {String} 
   * @param address {String} 
   * @param address2 {String} 
   * @param city {String} 
   * @param state {String} 
   * @param postalCode {String} 
   * @param zip4 {String} 
   * @param phoneNumber {String} 
   * @param email {String} 
   * @param pAddress {String} 
   * @param pAddress2 {String} 
   * @param pCity {String} 
   * @param pState {String} 
   * @param pPostalCode {String} 
   * @param pZip4 {String} 
   */
  var exports = function(companyName, companyLegal, address, address2, city, state, postalCode, zip4, phoneNumber, email, pAddress, pAddress2, pCity, pState, pPostalCode, pZip4) {
    var _this = this;

    _this['company_name'] = companyName;
    _this['company_legal'] = companyLegal;
    _this['address'] = address;
    _this['address2'] = address2;
    _this['city'] = city;
    _this['state'] = state;
    _this['postal_code'] = postalCode;
    _this['zip4'] = zip4;
    _this['phone_number'] = phoneNumber;
    _this['email'] = email;
    _this['p_address'] = pAddress;
    _this['p_address2'] = pAddress2;
    _this['p_city'] = pCity;
    _this['p_state'] = pState;
    _this['p_postal_code'] = pPostalCode;
    _this['p_zip4'] = pZip4;
  };

  /**
   * Constructs a <code>Updatecontact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Updatecontact} obj Optional instance to populate.
   * @return {module:model/Updatecontact} The populated <code>Updatecontact</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('company_name')) {
        obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
      }
      if (data.hasOwnProperty('company_legal')) {
        obj['company_legal'] = ApiClient.convertToType(data['company_legal'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('address2')) {
        obj['address2'] = ApiClient.convertToType(data['address2'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('postal_code')) {
        obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
      }
      if (data.hasOwnProperty('zip4')) {
        obj['zip4'] = ApiClient.convertToType(data['zip4'], 'String');
      }
      if (data.hasOwnProperty('phone_number')) {
        obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('p_address')) {
        obj['p_address'] = ApiClient.convertToType(data['p_address'], 'String');
      }
      if (data.hasOwnProperty('p_address2')) {
        obj['p_address2'] = ApiClient.convertToType(data['p_address2'], 'String');
      }
      if (data.hasOwnProperty('p_city')) {
        obj['p_city'] = ApiClient.convertToType(data['p_city'], 'String');
      }
      if (data.hasOwnProperty('p_state')) {
        obj['p_state'] = ApiClient.convertToType(data['p_state'], 'String');
      }
      if (data.hasOwnProperty('p_postal_code')) {
        obj['p_postal_code'] = ApiClient.convertToType(data['p_postal_code'], 'String');
      }
      if (data.hasOwnProperty('p_zip4')) {
        obj['p_zip4'] = ApiClient.convertToType(data['p_zip4'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} company_name
   */
  exports.prototype['company_name'] = undefined;
  /**
   * @member {String} company_legal
   */
  exports.prototype['company_legal'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {String} address2
   */
  exports.prototype['address2'] = undefined;
  /**
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} postal_code
   */
  exports.prototype['postal_code'] = undefined;
  /**
   * @member {String} zip4
   */
  exports.prototype['zip4'] = undefined;
  /**
   * @member {String} phone_number
   */
  exports.prototype['phone_number'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} p_address
   */
  exports.prototype['p_address'] = undefined;
  /**
   * @member {String} p_address2
   */
  exports.prototype['p_address2'] = undefined;
  /**
   * @member {String} p_city
   */
  exports.prototype['p_city'] = undefined;
  /**
   * @member {String} p_state
   */
  exports.prototype['p_state'] = undefined;
  /**
   * @member {String} p_postal_code
   */
  exports.prototype['p_postal_code'] = undefined;
  /**
   * @member {String} p_zip4
   */
  exports.prototype['p_zip4'] = undefined;



  return exports;
}));


