/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Account', 'model/Aclgroup', 'model/Acluser', 'model/Createcompany', 'model/Creategroup', 'model/Createuser', 'model/Deposits', 'model/Documents', 'model/ErrorResponse', 'model/GeneralResponse', 'model/Merchant', 'model/Owner', 'model/Ownerr', 'model/Reset', 'model/Setting', 'model/Transaction', 'model/Updatecompany', 'model/Updatecontact', 'model/Updateuser', 'api/CreateCompanyApi', 'api/GetListOfCompaniesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Account'), require('./model/Aclgroup'), require('./model/Acluser'), require('./model/Createcompany'), require('./model/Creategroup'), require('./model/Createuser'), require('./model/Deposits'), require('./model/Documents'), require('./model/ErrorResponse'), require('./model/GeneralResponse'), require('./model/Merchant'), require('./model/Owner'), require('./model/Ownerr'), require('./model/Reset'), require('./model/Setting'), require('./model/Transaction'), require('./model/Updatecompany'), require('./model/Updatecontact'), require('./model/Updateuser'), require('./api/CreateCompanyApi'), require('./api/GetListOfCompaniesApi'));
  }
}(function(ApiClient, Account, Aclgroup, Acluser, Createcompany, Creategroup, Createuser, Deposits, Documents, ErrorResponse, GeneralResponse, Merchant, Owner, Ownerr, Reset, Setting, Transaction, Updatecompany, Updatecontact, Updateuser, CreateCompanyApi, GetListOfCompaniesApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var PaysafeApi = require('index'); // See note below*.
   * var xxxSvc = new PaysafeApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new PaysafeApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new PaysafeApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new PaysafeApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Account model constructor.
     * @property {module:model/Account}
     */
    Account: Account,
    /**
     * The Aclgroup model constructor.
     * @property {module:model/Aclgroup}
     */
    Aclgroup: Aclgroup,
    /**
     * The Acluser model constructor.
     * @property {module:model/Acluser}
     */
    Acluser: Acluser,
    /**
     * The Createcompany model constructor.
     * @property {module:model/Createcompany}
     */
    Createcompany: Createcompany,
    /**
     * The Creategroup model constructor.
     * @property {module:model/Creategroup}
     */
    Creategroup: Creategroup,
    /**
     * The Createuser model constructor.
     * @property {module:model/Createuser}
     */
    Createuser: Createuser,
    /**
     * The Deposits model constructor.
     * @property {module:model/Deposits}
     */
    Deposits: Deposits,
    /**
     * The Documents model constructor.
     * @property {module:model/Documents}
     */
    Documents: Documents,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The GeneralResponse model constructor.
     * @property {module:model/GeneralResponse}
     */
    GeneralResponse: GeneralResponse,
    /**
     * The Merchant model constructor.
     * @property {module:model/Merchant}
     */
    Merchant: Merchant,
    /**
     * The Owner model constructor.
     * @property {module:model/Owner}
     */
    Owner: Owner,
    /**
     * The Ownerr model constructor.
     * @property {module:model/Ownerr}
     */
    Ownerr: Ownerr,
    /**
     * The Reset model constructor.
     * @property {module:model/Reset}
     */
    Reset: Reset,
    /**
     * The Setting model constructor.
     * @property {module:model/Setting}
     */
    Setting: Setting,
    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction: Transaction,
    /**
     * The Updatecompany model constructor.
     * @property {module:model/Updatecompany}
     */
    Updatecompany: Updatecompany,
    /**
     * The Updatecontact model constructor.
     * @property {module:model/Updatecontact}
     */
    Updatecontact: Updatecontact,
    /**
     * The Updateuser model constructor.
     * @property {module:model/Updateuser}
     */
    Updateuser: Updateuser,
    /**
     * The CreateCompanyApi service constructor.
     * @property {module:api/CreateCompanyApi}
     */
    CreateCompanyApi: CreateCompanyApi,
    /**
     * The GetListOfCompaniesApi service constructor.
     * @property {module:api/GetListOfCompaniesApi}
     */
    GetListOfCompaniesApi: GetListOfCompaniesApi
  };

  return exports;
}));
