/**
 * Paysafe Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PaysafeApi);
  }
}(this, function(expect, PaysafeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PaysafeApi.CreateCompanyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateCompanyApi', function() {
    describe('companiesIdContactGet', function() {
      it('should call companiesIdContactGet successfully', function(done) {
        //uncomment below and update the code to test companiesIdContactGet
        //instance.companiesIdContactGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesIdContactPost', function() {
      it('should call companiesIdContactPost successfully', function(done) {
        //uncomment below and update the code to test companiesIdContactPost
        //instance.companiesIdContactPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesIdDelete', function() {
      it('should call companiesIdDelete successfully', function(done) {
        //uncomment below and update the code to test companiesIdDelete
        //instance.companiesIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesIdGet', function() {
      it('should call companiesIdGet successfully', function(done) {
        //uncomment below and update the code to test companiesIdGet
        //instance.companiesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesIdPost', function() {
      it('should call companiesIdPost successfully', function(done) {
        //uncomment below and update the code to test companiesIdPost
        //instance.companiesIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesPost', function() {
      it('should call companiesPost successfully', function(done) {
        //uncomment below and update the code to test companiesPost
        //instance.companiesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('groupsIdDelete', function() {
      it('should call groupsIdDelete successfully', function(done) {
        //uncomment below and update the code to test groupsIdDelete
        //instance.groupsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('groupsIdGet', function() {
      it('should call groupsIdGet successfully', function(done) {
        //uncomment below and update the code to test groupsIdGet
        //instance.groupsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('groupsIdPost', function() {
      it('should call groupsIdPost successfully', function(done) {
        //uncomment below and update the code to test groupsIdPost
        //instance.groupsIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('groupsIdTogglePost', function() {
      it('should call groupsIdTogglePost successfully', function(done) {
        //uncomment below and update the code to test groupsIdTogglePost
        //instance.groupsIdTogglePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('groupsIdUsersPost', function() {
      it('should call groupsIdUsersPost successfully', function(done) {
        //uncomment below and update the code to test groupsIdUsersPost
        //instance.groupsIdUsersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('groupsPost', function() {
      it('should call groupsPost successfully', function(done) {
        //uncomment below and update the code to test groupsPost
        //instance.groupsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdAccountPost', function() {
      it('should call paymentsIdAccountPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdAccountPost
        //instance.paymentsIdAccountPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdDepositsBankPost', function() {
      it('should call paymentsIdDepositsBankPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdDepositsBankPost
        //instance.paymentsIdDepositsBankPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdDocumentsPost', function() {
      it('should call paymentsIdDocumentsPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdDocumentsPost
        //instance.paymentsIdDocumentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdOwnerAddressPost', function() {
      it('should call paymentsIdOwnerAddressPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdOwnerAddressPost
        //instance.paymentsIdOwnerAddressPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdOwnerPost', function() {
      it('should call paymentsIdOwnerPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdOwnerPost
        //instance.paymentsIdOwnerPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdSettingPost', function() {
      it('should call paymentsIdSettingPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdSettingPost
        //instance.paymentsIdSettingPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsIdTransactionPost', function() {
      it('should call paymentsIdTransactionPost successfully', function(done) {
        //uncomment below and update the code to test paymentsIdTransactionPost
        //instance.paymentsIdTransactionPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsPost', function() {
      it('should call paymentsPost successfully', function(done) {
        //uncomment below and update the code to test paymentsPost
        //instance.paymentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersIdDelete', function() {
      it('should call usersIdDelete successfully', function(done) {
        //uncomment below and update the code to test usersIdDelete
        //instance.usersIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersIdGet', function() {
      it('should call usersIdGet successfully', function(done) {
        //uncomment below and update the code to test usersIdGet
        //instance.usersIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersIdGroupsPost', function() {
      it('should call usersIdGroupsPost successfully', function(done) {
        //uncomment below and update the code to test usersIdGroupsPost
        //instance.usersIdGroupsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersIdPost', function() {
      it('should call usersIdPost successfully', function(done) {
        //uncomment below and update the code to test usersIdPost
        //instance.usersIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersIdResetPost', function() {
      it('should call usersIdResetPost successfully', function(done) {
        //uncomment below and update the code to test usersIdResetPost
        //instance.usersIdResetPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersIdTogglePost', function() {
      it('should call usersIdTogglePost successfully', function(done) {
        //uncomment below and update the code to test usersIdTogglePost
        //instance.usersIdTogglePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('usersPost', function() {
      it('should call usersPost successfully', function(done) {
        //uncomment below and update the code to test usersPost
        //instance.usersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
