/*
 * Paysafe Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Transaction struct {
	TrxVolume string `json:"trx_volume"`
	TrxAverage string `json:"trx_average"`
	TrxHigh string `json:"trx_high"`
	PreviouslyAccepted string `json:"previously_accepted"`
	Acceptance string `json:"acceptance"`
	CardPresent string `json:"card_present"`
	ShipGoods string `json:"ship_goods"`
	DeliveryTime string `json:"delivery_time"`
}
