/*
 * Paysafe Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Owner struct {
	OwnerCtime string `json:"owner_ctime"`
	OwnerAddress string `json:"owner_address"`
	OwnerAddress2 string `json:"owner_address2"`
	OwnerCity string `json:"owner_city"`
	OwnerState string `json:"owner_state"`
	OwnerZip string `json:"owner_zip"`
	OwnerZip4 string `json:"owner_zip4"`
	OwnerPtime string `json:"owner_ptime"`
	OwnerPaddress string `json:"owner_paddress"`
	OwnerPaddress2 string `json:"owner_paddress2"`
	OwnerPcity string `json:"owner_pcity"`
	OwnerPstate string `json:"owner_pstate"`
	OwnerPzip string `json:"owner_pzip"`
	OwnerPzip4 string `json:"owner_pzip4"`
}
