/*
 * Paysafe Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Documents struct {
	Type_ string `json:"type"`
	Number string `json:"number"`
	Issuedby string `json:"issuedby"`
	IssuedDay string `json:"issued_day"`
	IssuedMonth string `json:"issued_month"`
	IssuedYear string `json:"issued_year"`
	ExpiresDay string `json:"expires_day"`
	ExpiresMonth string `json:"expires_month"`
	ExpiresYear string `json:"expires_year"`
}
