/*
 * Paysafe Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Updatecontact struct {
	CompanyName string `json:"company_name"`
	CompanyLegal string `json:"company_legal"`
	Address string `json:"address"`
	Address2 string `json:"address2"`
	City string `json:"city"`
	State string `json:"state"`
	PostalCode string `json:"postal_code"`
	Zip4 string `json:"zip4"`
	PhoneNumber string `json:"phone_number"`
	Email string `json:"email"`
	PAddress string `json:"p_address"`
	PAddress2 string `json:"p_address2"`
	PCity string `json:"p_city"`
	PState string `json:"p_state"`
	PPostalCode string `json:"p_postal_code"`
	PZip4 string `json:"p_zip4"`
}
