/*
 * Paysafe Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Setting struct {
	Currency string `json:"currency"`
	AmexId string `json:"amex_id"`
	Descriptor string `json:"descriptor"`
	Locale string `json:"locale"`
	Lang string `json:"lang"`
	DescriptorPhone string `json:"descriptor_phone"`
}
