/*
 * Paysafe Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Ownerr struct {
	NameFirst string `json:"name_first"`
	NameLast string `json:"name_last"`
	JobTitle string `json:"job_title"`
	Day string `json:"day"`
	Month string `json:"month"`
	Year string `json:"year"`
	Gender string `json:"gender"`
	Nationality string `json:"nationality"`
	Taxid string `json:"taxid"`
	Percentage string `json:"percentage"`
}
