/*
 * Paysafe Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Account struct {
	CompanyName string `json:"company_name"`
	Legal string `json:"legal"`
	Type_ string `json:"type"`
	Vat string `json:"vat"`
	Website string `json:"website"`
	StartDate string `json:"start_date"`
}
