# coding: utf-8

"""
    Paysafe Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.acluser import Acluser  # noqa: E501
from swagger_client.rest import ApiException


class TestAcluser(unittest.TestCase):
    """Acluser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcluser(self):
        """Test Acluser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.acluser.Acluser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
