# coding: utf-8

"""
    Paysafe Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.create_company_api import CreateCompanyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateCompanyApi(unittest.TestCase):
    """CreateCompanyApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.create_company_api.CreateCompanyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_id_contact_get(self):
        """Test case for companies_id_contact_get

        """
        pass

    def test_companies_id_contact_post(self):
        """Test case for companies_id_contact_post

        """
        pass

    def test_companies_id_delete(self):
        """Test case for companies_id_delete

        """
        pass

    def test_companies_id_get(self):
        """Test case for companies_id_get

        """
        pass

    def test_companies_id_post(self):
        """Test case for companies_id_post

        """
        pass

    def test_companies_post(self):
        """Test case for companies_post

        """
        pass

    def test_groups_id_delete(self):
        """Test case for groups_id_delete

        """
        pass

    def test_groups_id_get(self):
        """Test case for groups_id_get

        """
        pass

    def test_groups_id_post(self):
        """Test case for groups_id_post

        """
        pass

    def test_groups_id_toggle_post(self):
        """Test case for groups_id_toggle_post

        """
        pass

    def test_groups_id_users_post(self):
        """Test case for groups_id_users_post

        """
        pass

    def test_groups_post(self):
        """Test case for groups_post

        """
        pass

    def test_payments_id_account_post(self):
        """Test case for payments_id_account_post

        """
        pass

    def test_payments_id_deposits_bank_post(self):
        """Test case for payments_id_deposits_bank_post

        """
        pass

    def test_payments_id_documents_post(self):
        """Test case for payments_id_documents_post

        """
        pass

    def test_payments_id_owner_address_post(self):
        """Test case for payments_id_owner_address_post

        """
        pass

    def test_payments_id_owner_post(self):
        """Test case for payments_id_owner_post

        """
        pass

    def test_payments_id_setting_post(self):
        """Test case for payments_id_setting_post

        """
        pass

    def test_payments_id_transaction_post(self):
        """Test case for payments_id_transaction_post

        """
        pass

    def test_payments_post(self):
        """Test case for payments_post

        """
        pass

    def test_users_id_delete(self):
        """Test case for users_id_delete

        """
        pass

    def test_users_id_get(self):
        """Test case for users_id_get

        """
        pass

    def test_users_id_groups_post(self):
        """Test case for users_id_groups_post

        """
        pass

    def test_users_id_post(self):
        """Test case for users_id_post

        """
        pass

    def test_users_id_reset_post(self):
        """Test case for users_id_reset_post

        """
        pass

    def test_users_id_toggle_post(self):
        """Test case for users_id_toggle_post

        """
        pass

    def test_users_post(self):
        """Test case for users_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
