# coding: utf-8

"""
    Paysafe Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.get_list_of_companies_api import GetListOfCompaniesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGetListOfCompaniesApi(unittest.TestCase):
    """GetListOfCompaniesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.get_list_of_companies_api.GetListOfCompaniesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_companies_get(self):
        """Test case for companies_get

        """
        pass

    def test_groups_get(self):
        """Test case for groups_get

        """
        pass

    def test_users_get(self):
        """Test case for users_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
