# coding: utf-8

"""
    Paysafe Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.documents import Documents  # noqa: E501
from swagger_client.rest import ApiException


class TestDocuments(unittest.TestCase):
    """Documents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocuments(self):
        """Test Documents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.documents.Documents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
